import type { AgentTransformer, TransformResult } from '../transformer.js';
import { WORKFLOW_SKILLS, simplifyFrontmatter } from '../transformer.js';
import { writeTextFile } from '../../utils/fs.js';
import path from 'path';

export class AntigravityTransformer implements AgentTransformer {
  transform(skillName: string, content: string): TransformResult {
    if (WORKFLOW_SKILLS.has(skillName)) {
      return {
        targetDir: 'workflows',
        targetName: `flz.${skillName}.md`,
        content: simplifyFrontmatter(content),
        flat: true,
      };
    }

    return {
      targetDir: skillName,
      targetName: 'SKILL.md',
      content,
      flat: false,
    };
  }

  async postInstall(projectDir: string): Promise<void> {
    const rulesDir = path.join(projectDir, '.agent', 'rules');

    const guardrailsContent = `# FLZ Guardrails

## Project Conventions

- Follow existing code style and patterns in the project
- Use conventional commits format for all commit messages
- Always check for existing implementations before creating new ones
- Prefer editing existing files over creating new ones
- Run tests after making changes when test infrastructure exists

## Skill Usage

- Use \`/flz.feature\` for new features — creates branch, plan, and tasks
- Use \`/flz.fix\` for bug fixes — analyzes, fixes, suggests tests
- Use \`/flz.commit\` for commits — follows conventional commits
- Use \`/flz.implement\` to execute plans step by step
- Use \`/flz.review\` before merging — checks code quality

## Safety

- Never commit secrets, tokens, or credentials
- Never force-push to main/master branches
- Always create feature branches for new work
`;

    const conventionsContent = `# FLZ Conventions

## Workflow Structure

FLZ organizes skills into three categories:

### Workflows (.agent/workflows/)
Action-oriented skills that execute specific tasks:
- \`flz.feature.md\` — Plan and develop new features
- \`flz.fix.md\` — Fix bugs with structured approach
- \`flz.implement.md\` — Execute plans step by step
- \`flz.commit.md\` — Create conventional commits
- \`flz.review.md\` — Code review checklist
- \`flz.deploy.md\` — Deployment automation
- \`flz.ci.md\` — CI/CD pipeline setup

### Skills (.agent/skills/)
Knowledge-based skills providing guidelines and patterns:
- \`best-practices/\` — Code quality standards
- \`architecture/\` — Architecture decision records
- Stack-specific skills generated by \`/flz\`

### Rules (.agent/rules/)
Always-active guardrails and conventions that apply to every interaction.

## Naming Convention

- Workflow files: \`flz.{action}.md\` (flat files)
- Skill directories: \`{skill-name}/SKILL.md\` (with supporting files)
- Rule files: \`flz-{rule-name}.md\`
`;

    await writeTextFile(path.join(rulesDir, 'flz-guardrails.md'), guardrailsContent);
    await writeTextFile(path.join(rulesDir, 'flz-conventions.md'), conventionsContent);
  }

  getWelcomeMessage(): string[] {
    return [
      '1. Open Antigravity in this directory',
      '2. Action skills installed as workflows in .agent/workflows/ (flat files)',
      '3. Knowledge skills installed in .agent/skills/ (directories)',
      '4. Rules installed in .agent/rules/ (guardrails and conventions)',
      '5. Run /flz to analyze project and generate stack-specific skills',
    ];
  }
}
