import type { AgentTransformer, TransformResult } from '../transformer.js';
import { WORKFLOW_SKILLS, simplifyFrontmatter } from '../transformer.js';
import { writeTextFile } from '../../utils/fs.js';
import path from 'path';

export class AntigravityTransformer implements AgentTransformer {
  transform(skillName: string, content: string): TransformResult {
    if (WORKFLOW_SKILLS.has(skillName)) {
      return {
        targetDir: 'workflows',
        targetName: `${skillName}.md`,
        content: simplifyFrontmatter(content),
        flat: true,
      };
    }

    return {
      targetDir: skillName,
      targetName: 'SKILL.md',
      content,
      flat: false,
    };
  }

  async postInstall(projectDir: string): Promise<void> {
    const rulesDir = path.join(projectDir, '.agent', 'rules');

    const guardrailsContent = `# AI Factory Guardrails

## Project Conventions

- Follow existing code style and patterns in the project
- Use conventional commits format for all commit messages
- Always check for existing implementations before creating new ones
- Prefer editing existing files over creating new ones
- Run tests after making changes when test infrastructure exists

## Skill Usage

- Use \`/ai-factory-feature\` for new features — creates branch, plan, and tasks
- Use \`/ai-factory-fix\` for bug fixes — analyzes, fixes, suggests tests
- Use \`/ai-factory-commit\` for commits — follows conventional commits
- Use \`/ai-factory-implement\` to execute plans step by step
- Use \`/ai-factory-review\` before merging — checks code quality

## Safety

- Never commit secrets, tokens, or credentials
- Never force-push to main/master branches
- Always create feature branches for new work
`;

    const conventionsContent = `# AI Factory Conventions

## Workflow Structure

AI Factory organizes skills into three categories:

### Workflows (.agent/workflows/)
Action-oriented skills that execute specific tasks:
- \`ai-factory-feature.md\` — Plan and develop new features
- \`ai-factory-fix.md\` — Fix bugs with structured approach
- \`ai-factory-implement.md\` — Execute plans step by step
- \`ai-factory-commit.md\` — Create conventional commits
- \`ai-factory-review.md\` — Code review checklist
- \`ai-factory-deploy.md\` — Deployment automation
- \`ai-factory-ci.md\` — CI/CD pipeline setup

### Skills (.agent/skills/)
Knowledge-based skills providing guidelines and patterns:
- \`best-practices/\` — Code quality standards
- \`architecture/\` — Architecture decision records
- Stack-specific skills generated by \`/ai-factory\`

### Rules (.agent/rules/)
Always-active guardrails and conventions that apply to every interaction.

## Naming Convention

- Workflow files: \`ai-factory-{action}.md\` (flat files)
- Skill directories: \`{skill-name}/SKILL.md\` (with supporting files)
- Rule files: \`ai-factory-{rule-name}.md\`
`;

    await writeTextFile(path.join(rulesDir, 'ai-factory-guardrails.md'), guardrailsContent);
    await writeTextFile(path.join(rulesDir, 'ai-factory-conventions.md'), conventionsContent);
  }

  getWelcomeMessage(): string[] {
    return [
      '1. Open Antigravity in this directory',
      '2. Action skills installed as workflows in .agent/workflows/ (flat files)',
      '3. Knowledge skills installed in .agent/skills/ (directories)',
      '4. Rules installed in .agent/rules/ (guardrails and conventions)',
      '5. Run /ai-factory to analyze project and generate stack-specific skills',
    ];
  }
}
